#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Configure SwiftySwiftVim.."
$DIR/configure

echo "Build SwiftySwiftVim.."
make -C build

echo "Bootstrap SwiftySwiftVim is a go!"

